[project]
name = "web-crawler"
version = "0.1.0"
description = ""
packages = [{ include = "web_crawler" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
core = {path="../../shared", develop=true}
crawl4ai = "^0.5.0.post8" 

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
